### ISSUE TITLE
本地不存在config.xml中jar时处理

### ISSUE THREAD

**Issue by jonesun** [update4j/demo#2]
我使用了java -jar update4j-1.5.6.jar --remote xxx， 我需要确保config.xml中的所有jar必须事先存才能正常更新吗? 
否则会报类似以下错误：
```
java.lang.IllegalStateException: Size of file 'controlsfx-9.0.0.jar' does not match size in configuration. Expected: 946412, found: 239
        at org.update4j.ConfigImpl.validateFile(ConfigImpl.java:461)
        at org.update4j.ConfigImpl.doUpdate(ConfigImpl.java:369)
        at org.update4j.Configuration.update(Configuration.java:915)
        at org.update4j.service.DefaultBootstrap.updateFirst(DefaultBootstrap.java:206)
        at org.update4j.service.DefaultBootstrap.main(DefaultBootstrap.java:147)
        at org.update4j.Bootstrap.start(Bootstrap.java:297)
        at org.update4j.Bootstrap.start(Bootstrap.java:280)
        at org.update4j.Bootstrap.start(Bootstrap.java:182)
        at org.update4j.Bootstrap.main(Bootstrap.java:113)
```
但是经常出现的是项目开发更新后会增加一些库(jar)引用，不会事先知道项目中会添加哪些引用，请问这个可以怎么解决？

**Comment by jonesun** [comment]
The problem has already been solved.
